# Use official Node.js image
#FROM node:20

# Create app directory
#WORKDIR /usr/src/app

# Copy and install dependencies
#COPY package*.json ./
#RUN npm install

# Copy source files
#COPY . .

# Expose port and start app
#EXPOSE 3000
#CMD [ "npm", "start" ]

FROM node:18
WORKDIR /app

# Copy package.json and package-lock.json first (this allows Docker to cache the dependencies)
COPY package.json package-lock.json ./

#ENV NODE_ENV=test can be used for testing
#if (process.env.NODE_ENV === 'development') {
#    console.log("Running in dev mode");
#}
#mode: process.env.NODE_ENV === 'production' ? 'production' : 'development'
ENV NODE_ENV=development 
RUN npm install 

# Copy the rest of the frontend application code
#COPY src /app/src #Bind mount in yml file takes care of these steps
#COPY public /app/public

#RUN npm run build #Bind mount in yml file takes care of these steps

EXPOSE 3000
CMD ["npm", "start"]