# Use official Node.js image
#FROM node:20

# Create app directory
#WORKDIR /usr/src/app

# Copy and install dependencies
#COPY package*.json ./
#RUN npm install

# Copy source files
#COPY . .

# Expose port and start app
#EXPOSE 3000
#CMD [ "npm", "start" ]

FROM node:18
WORKDIR /app

# Copy package.json and package-lock.json first (this allows Docker to cache the dependencies)
COPY package.json package-lock.json ./

#Can refer in frontend code like this.
#if (process.env.NODE_ENV === 'production') {
#// Production-specific logic
#}
ENV NODE_ENV=production
RUN npm install --omit=dev

# Copy the rest of the frontend application code
COPY src /app/src
COPY public /app/public

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]