events {}

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;
  client_max_body_size 50M;

  # HTTP block to redirect to HTTPS
  server {
    listen 80;
    server_name localhost;

    return 301 https://$host$request_uri;
  }

  # HTTPS block
  server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/letsencrypt/live/suct.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/suct.in/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # React App
    location / {
      proxy_pass http://frontend:3000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_cache_bypass $http_upgrade;
    }

    # Node.js Backend
    location /api/ {
      proxy_pass http://backend:5000/;
      proxy_set_header Host $host;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_cache_bypass $http_upgrade;
    }

    # NocoDB
    location /nocodb/ {
      rewrite ^/nocodb(/.*)$ $1 break;
      proxy_pass http://nocodb:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
    }

    # Adminer
    location /adminer/ {
      rewrite ^/adminer(/.*)$ $1 break;
      proxy_pass http://adminer:8080;
    }

    # PHP App
    location /php/ {
      rewrite ^/php(/.*)$ $1 break;
      proxy_pass http://phpapp:80;
    }
  }
}

