# Use official Node.js image
#FROM node:20

# Create app directory
#WORKDIR /usr/src/app

# Copy and install dependencies
#COPY package*.json ./
#RUN npm install

# Copy source files
#COPY . .

# Expose port and start app
#EXPOSE 3000
#C0MD [ "npm", "start" ]

FROM node:16
WORKDIR /app

# Copy package.json and package-lock.json for backend dependencies
COPY package.json package-lock.json ./

#Can refer in backend code like this.
#if (process.env.NODE_ENV === 'production') {
#// Production-specific logic
#}
ENV NODE_ENV=production
RUN npm install --omit=dev

# Copy the backend source code into the container
COPY . /app

EXPOSE 5000
CMD ["node", "app.js"]